name: CI Tienda Perritos - Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar carpeta Backend
        run: |
          ls
          test -d backend

      - name: Verificar Dockerfile
        run: |
          test -f backend/Dockerfile

      - name: Build imagen Backend
        run: |
          cd backend
          docker build -t tienda-backend .

      - name: Ver imágenes Docker
        run: |
          docker images